name: deepjetLinux3
channels:
  - NLeSC
  - defaults
dependencies:
  - fftw=3.3.4=2
  - gcc=4.8.2=25
  - glibc=2.12.2=3
  - gmp=5.1.2=3
  - graphviz=2.38.0=4
  - gsl=1.16=2
  - isl=0.12.2=2
  - linux-headers=2.6.32=1
  - mpc=1.0.1=2
  - mpfr=3.1.2=2
  - pcre=8.37=5
  - root=6.04=py2.7_gcc4.8.2
  - root-numpy=4.4.0=root6.04_py2.7
  - boost=1.61.0=py27_0
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2018.1.18=py27_0
  - cloog=0.18.0=0
  - dbus=1.10.10=0
  - expat=2.1.0=0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - glib=2.43.0=1
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=0
  - hdf5=1.8.17=1
  - icu=54.1=0
  - jbig=2.1=0
  - jpeg=9b=0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=1
  - libgcc=5.2.0=0
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran=3.0.0=1
  - libiconv=1.14=0
  - libpng=1.6.27=0
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libtiff=4.0.6=3
  - libxcb=1.12=1
  - libxml2=2.9.4=0
  - mkl=2017.0.1=0
  - ncurses=6.0=h9df7e31_2
  - numexpr=2.6.2=np113py27_0
  - numpy=1.13.1=py27_0
  - openssl=1.0.1k=1
  - pip=9.0.1=py27_1
  - pytables=3.3.0=np113py27_0
  - python=2.7.5=3
  - qt=5.6.2=3
  - readline=6.2=2
  - scikit-learn=0.18.2=np113py27_0
  - scipy=0.19.1=np113py27_0
  - setuptools=27.2.0=py27_0
  - six=1.10.0=py27_0
  - sqlite=3.13.0=0
  - system=5.8=2
  - tk=8.5.18=0
  - wheel=0.29.0=py27_0
  - xz=5.2.2=1
  - zlib=1.2.8=3
  - pip:
    - cycler==0.10.0
    - funcsigs==1.0.2
    - functools32==3.2.3.post2
    - h5py==2.6.0
    - keras==2.0.0
    - matplotlib==2.0.0
    - mock==2.0.0
    - pbr==2.0.0
    - protobuf==3.2.0
    - pyparsing==2.2.0
    - python-dateutil==2.6.0
    - pytz==2016.10
    - pyyaml==3.12
    - subprocess32==3.2.7
    - tables==3.3.0
    - tensorflow==1.0.1
